# Site settings
title: "Owl Games"
description: "Owl Games - Making great games!"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Owl Games"
resume_title:                   "Making great games!"
resume_contact_email:           "owlgamesstudio@gmail.com"
resume_contact_telephone:       ""
resume_contact_address:         ""
resume_header_contact_info: ""
resume_header_intro: "<p>Owl Games is curently making mobile games as a hobby. We're getting started with by re-making classic games as free to play  with a high standard of quality and no advertising (because no one likes ads) or in app purchase.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_products:   	true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/gheaeckkseqrz/"
  resume_twitter_url:           "https://twitter.com/owlgamesstudio"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/owlgamesstudios/"
  resume_linkedin_url:          "https://www.linkedin.com/company/owl-games/"
  resume_instagram_url:         "https://www.instagram.com/owlgamesstudio/"
  #resume_website_url:           "https://gheaeckkseqrz.wordpress.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman